### PR TITLE
Added initial steps to force push functionality.

### PR DESCRIPTION
**Pull request by zeyus**
see https://github.com/integratedexperts/robo-git-artefact/issues/2

This PR is just a placeholder. It's not functionally complete.

### CODE REVIEW

**Comment by alexdesignworks** [comment]
@zeyus 
Looks good so far. 
Re naming of the option `--mirror` - it may be a bit confusing as it does not actually mirrors the repo - it squashes commits from `src` repo. Can we name it differently?

Also, are you planning to add the logic to squash commits and create a deployment commit OR have you found a better way to do this? (which would be awesome)

**Comment by zeyus** [comment]
@alexdesignworks Yeah realised that with the name mirror, I think the `force` option name is probably better (to allow overwriting an existing branch with the same name).

For the squash part, I think we could also use the option name `squash` which will always make a commit with all the updates since the last one on the remote.

Something like this method should work: https://stackoverflow.com/a/5190323

**Comment by alexdesignworks** [comment]
`force` would be a bit misleading again - as in "git forced push", which is not what this command is.

We cannot force-push new data to `dst` as the branch could be already deployed  - can only add as additional commits,

**Comment by zeyus** [comment]
`--update-remote` ?

**Comment by alexdesignworks** [comment]
closed in favour of fully refactored solution

**Pull request closed without merging**
